In [1]:
import pandas as pd

In [2]:
with open("Next Word Predictor Dataset.txt", "r", encoding="utf-8") as f:
    data = f.readlines()

In [3]:
df = pd.DataFrame(data, columns=["text"])

In [4]:
df.head(10)

                                                text
0                 I hope this email finds you well\n
1               Thank you for your prompt response\n
2  I appreciate your valuable input on this matter\n
3  Please find attached the document you requested\n
4  I am writing to inform you about the upcoming ...
5    Your attention to detail is truly commendable\n
6  I wanted to follow up on our recent conversati...
7  It was a pleasure meeting you at the conference\n
8  I am reaching out to discuss potential collabo...
9  I wanted to express my gratitude for your supp...

In [5]:
df['text'] = df['text'].str.strip()

In [6]:
df.shape

(4636, 1)

In [7]:
df.isnull().sum()

text    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(1300)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
data = []
for i in range(0, df.shape[0]):
    df['text'] = df['text'].str.lower()
    words_list = df['text'].iloc[i].split() 
    for j in range(1, len(words_list) + 1):
        data.append(words_list[:j])

In [11]:
new_df = pd.DataFrame({"text": data})

In [12]:
new_df.head(30)

                                                 text
0                                                 [i]
1                                           [i, hope]
2                                     [i, hope, this]
3                              [i, hope, this, email]
4                       [i, hope, this, email, finds]
5                  [i, hope, this, email, finds, you]
6            [i, hope, this, email, finds, you, well]
7                                             [thank]
8                                        [thank, you]
9                                   [thank, you, for]
10                            [thank, you, for, your]
11                    [thank, you, for, your, prompt]
12          [thank, you, for, your, prompt, response]
13                                                [i]
14                                    [i, appreciate]
15                              [i, appreciate, your]
16                    [i, appreciate, your, valuable]
17             [i, appreciate, your, valuable, input]
18         [i, appreciate, your, valuable, input, on]
19   [i, appreciate, your, valuable, input, on, this]
20  [i, appreciate, your, valuable, input, on, thi...
21                                           [please]
22                                     [please, find]
23                           [please, find, attached]
24                      [please, find, attached, the]
25            [please, find, attached, the, document]
26       [please, find, attached, the, document, you]
27  [please, find, attached, the, document, you, r...
28                                                [i]
29                                            [i, am]

In [13]:
new_df.shape

(35665, 1)

In [14]:
new_df.duplicated().sum()

np.int64(11716)

In [15]:
new_df.drop(new_df[new_df['text'].str.len() == 1].index, inplace=True)

In [16]:
new_df.drop_duplicates(inplace=True)

In [17]:
new_df['next_word'] = new_df['text'].str[-1]

In [18]:
new_df['text'] = new_df['text'].str[:-1]

In [19]:
new_df.head()

                            text next_word
1                            [i]      hope
2                      [i, hope]      this
3                [i, hope, this]     email
4         [i, hope, this, email]     finds
5  [i, hope, this, email, finds]       you

In [20]:
new_df['text'].str.len().max()

np.int64(19)

In [21]:
new_df.shape

(23790, 2)

In [22]:
new_df.info()

<class 'pandas.DataFrame'>
Index: 23790 entries, 1 to 35664
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       23790 non-null  object
 1   next_word  23790 non-null  object
dtypes: object(2)
memory usage: 557.6+ KB

In [23]:
print(new_df.shape)

print(new_df['text'].str.len().describe())

print(new_df.loc[new_df['text'].str.len().idxmax(), 'text'])

(23790, 2)
count    23790.000000
mean         6.674443
std          3.014932
min          1.000000
25%          4.000000
50%          7.000000
75%          9.000000
max         19.000000
Name: text, dtype: float64
['your', 'commitment', 'to', 'excellence', 'sets', 'a', 'high', 'standard', 'for', 'the', "teamlet's", 'schedule', 'a', 'conference', 'call', 'to', 'discuss', 'the', 'details']

In [24]:
print(type(new_df['text'].iloc[0]))

<class 'list'>

In [25]:
new_df.to_csv("preprocessed_data.csv", index=False)